#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Library")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKitaplar(Kitaplar instance);
    partial void UpdateKitaplar(Kitaplar instance);
    partial void DeleteKitaplar(Kitaplar instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LibraryConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kitaplar> Kitaplars
		{
			get
			{
				return this.GetTable<Kitaplar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kitaplar")]
	public partial class Kitaplar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ad;
		
		private string _Yazar;
		
		private System.Nullable<double> _Fiyat;
		
		private System.Nullable<int> _Sayfa_Sayisi;
		
		private System.Nullable<System.DateTime> _Alim_Tarihi;
		
		private System.Nullable<System.DateTime> _Okuma_Tarihi;
		
		private System.Nullable<int> _Son_Okunan_Sayfa;
		
		private System.Nullable<System.DateTime> _Bitiş_Tarihi;
		
		private string _ISBN;
		
		private System.Nullable<bool> _Durum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnYazarChanging(string value);
    partial void OnYazarChanged();
    partial void OnFiyatChanging(System.Nullable<double> value);
    partial void OnFiyatChanged();
    partial void OnSayfa_SayisiChanging(System.Nullable<int> value);
    partial void OnSayfa_SayisiChanged();
    partial void OnAlim_TarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnAlim_TarihiChanged();
    partial void OnOkuma_TarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOkuma_TarihiChanged();
    partial void OnSon_Okunan_SayfaChanging(System.Nullable<int> value);
    partial void OnSon_Okunan_SayfaChanged();
    partial void OnBitiş_TarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnBitiş_TarihiChanged();
    partial void OnISBNChanging(string value);
    partial void OnISBNChanged();
    partial void OnDurumChanging(System.Nullable<bool> value);
    partial void OnDurumChanged();
    #endregion
		
		public Kitaplar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(MAX)")]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yazar", DbType="NVarChar(50)")]
		public string Yazar
		{
			get
			{
				return this._Yazar;
			}
			set
			{
				if ((this._Yazar != value))
				{
					this.OnYazarChanging(value);
					this.SendPropertyChanging();
					this._Yazar = value;
					this.SendPropertyChanged("Yazar");
					this.OnYazarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Float")]
		public System.Nullable<double> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sayfa_Sayisi", DbType="Int")]
		public System.Nullable<int> Sayfa_Sayisi
		{
			get
			{
				return this._Sayfa_Sayisi;
			}
			set
			{
				if ((this._Sayfa_Sayisi != value))
				{
					this.OnSayfa_SayisiChanging(value);
					this.SendPropertyChanging();
					this._Sayfa_Sayisi = value;
					this.SendPropertyChanged("Sayfa_Sayisi");
					this.OnSayfa_SayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alim_Tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Alim_Tarihi
		{
			get
			{
				return this._Alim_Tarihi;
			}
			set
			{
				if ((this._Alim_Tarihi != value))
				{
					this.OnAlim_TarihiChanging(value);
					this.SendPropertyChanging();
					this._Alim_Tarihi = value;
					this.SendPropertyChanged("Alim_Tarihi");
					this.OnAlim_TarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Okuma_Tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Okuma_Tarihi
		{
			get
			{
				return this._Okuma_Tarihi;
			}
			set
			{
				if ((this._Okuma_Tarihi != value))
				{
					this.OnOkuma_TarihiChanging(value);
					this.SendPropertyChanging();
					this._Okuma_Tarihi = value;
					this.SendPropertyChanged("Okuma_Tarihi");
					this.OnOkuma_TarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Son_Okunan_Sayfa", DbType="Int")]
		public System.Nullable<int> Son_Okunan_Sayfa
		{
			get
			{
				return this._Son_Okunan_Sayfa;
			}
			set
			{
				if ((this._Son_Okunan_Sayfa != value))
				{
					this.OnSon_Okunan_SayfaChanging(value);
					this.SendPropertyChanging();
					this._Son_Okunan_Sayfa = value;
					this.SendPropertyChanged("Son_Okunan_Sayfa");
					this.OnSon_Okunan_SayfaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bitiş_Tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Bitiş_Tarihi
		{
			get
			{
				return this._Bitiş_Tarihi;
			}
			set
			{
				if ((this._Bitiş_Tarihi != value))
				{
					this.OnBitiş_TarihiChanging(value);
					this.SendPropertyChanging();
					this._Bitiş_Tarihi = value;
					this.SendPropertyChanged("Bitiş_Tarihi");
					this.OnBitiş_TarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="NVarChar(MAX)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="Bit")]
		public System.Nullable<bool> Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
